language: cpp
os:
  - linux
  - osx
compiler:
- clang
script: 
  - bash ./build.sh

deploy:
  provider: releases
  api_key: 
    secure: $key
  file_glob: true
  file: build/*
  skip_cleanup: true
  on:
    tags: true