jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: bash build.sh
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'build'
      ArtifactName: '$(Agent.OS).$(Agent.OSArchitecture)'
      publishLocation: 'Container'
  
- job: macOS
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - script: bash build.sh
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'build'
      ArtifactName: '$(Agent.OS).$(Agent.OSArchitecture)'
      publishLocation: 'Container'
    

- job: Windows
  pool:
    vmImage: 'windows-2019'
  steps:
  - script: 'cmake .'
  - task: MSBuild@1
    inputs:
      solution: '**/*.sln'
      configuration: 'Debug'
      maximumCpuCount: true
  - task: MSBuild@1
    inputs:
      solution: '**/*.sln'
      configuration: 'Release'
      maximumCpuCount: true
  - task: MSBuild@1
    inputs:
      solution: '**/*.sln'
      configuration: 'Release'
      msbuildArchitecture: 'x64'
  - task: MSBuild@1
    inputs:
      solution: '**/*.sln'
      configuration: 'Debug'
      maximumCpuCount: true
      msbuildArchitecture: 'x64'
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'build'
      ArtifactName: '$(Agent.OS).$(Agent.OSArchitecture)'
      publishLocation: 'Container'
    