jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: bash build.sh
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'build'
      ArtifactName: '$(Agent.OS)'
      publishLocation: 'Container'
    
- job: macOS
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - script: bash build.sh
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'build'
      ArtifactName: '$(Agent.OS)'
      publishLocation: 'Container'
    

- job: Windows
  pool:
    vmImage: 'windows-2019'
  steps:
  - script: 'cmake .'
  - task: VSBuild@1
    inputs:
      solution: '**\*.sln'
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'build'
      ArtifactName: '$(Agent.OS)'
      publishLocation: 'Container'
    