#!./build/StarCore*
# Test File
cout("----------------------\n[TEST]Hello World!\n----------------------\n");
if(true);
cout("[TEST]True PASS\n----------------------\n");
end;
if(false);
else;
cout("[TEST]Else PASS\n----------------------\n");
end;
a="[TEST]";
if(a.equals("[TEST]"));
cout("[TEST]Var PASS\n----------------------\n");
else;
cout("[TEST]Var Failed\n----------------------\n");
end;
n=0;
count=10;
while(n.less(count));
cout("[TEST]While Loop:",n,"\r");
n=n+1;
end;
if(n.equals(count));
cout("[TEST]While PASS       \n----------------------\n");
else;
cout("[TEST]While Failed:",n,"\n----------------------\n");
end;
cout("[TEST]Operator test\n");
cout("1 + 1  = ",1+1,"\n");
cout("1 - 1  = ",1-1,"\n");
cout("5 * 5  = ",5*5,"\n");
cout("20 / 4 = ",20/4,"\n----------------------\n");
cout("[TEST]Nine-nine multiplication table test\n");
x=1;
y=1;
while(x.less(10));
while(y.less(10));
if(y.less(x));
cout(" ",y," * ",x," = ",x*y," ");
end;
if(y.equals(x));
cout(" ",y," * ",x," = ",x*y," ");
end;
y=y+1;
end;
x=x+1;
y=1;
cout("\n");
end;
cout("\n----------------------");