# EXAM.LOGIN
cout("Please set the password:"); 
cin(password);
is_loggout=true;
max_err=5;
err_count=0;
while(is_loggout.and(err_count.less(max_err)));
cout("Please input password:");
cin(str);
if(str.equals(password));
cout("Success\n");
is_loggout=false;
else;
cout("Error\n");
err_count=err_count.plus(1);
cout("You have ",max_err.minus(err_count)," times left to try\n");
end;
end;
if(err_count.equals(max_err));
cout("You account is disabled\n");
end;