#define TS_ID_1 "错误的数据库字符串"
#define TS_ID_2 "错误的数据组"
#define TS_ID_3 "错误的类型"
#define DB_START '\u0001'
#define TS_ID_4 "未找到"
#define TS_ID_5 "已存在"
#define TS_ID_6 "正在删除"
#define TS_ID_7 "正在插入"
#define TS_ID_8 "正在访问"
#define TS_ID_9 "创建空项来避免空指针"
#define CONF_FILE_NOTICE_MSG "# 配置文件\n"
#define TS_ID_10 "太多 '=' 号了"
#define TS_ID_11 "标识"
#define TS_ID_12 "无法打开文件"
#define TS_ID_13 "库未载入"
#define TS_ID_14 "库不存在"