#define TS_ID_1 "Invalid Database String"
#define TS_ID_2 "Invalid Group"
#define TS_ID_3 "Invalid Type"
#define DB_START '\u0001'
#define TS_ID_4 "Not Find"
#define TS_ID_5 "Already Exist"
#define TS_ID_6 "Removing"
#define TS_ID_7 "Inserting"
#define TS_ID_8 "Accessing"
#define TS_ID_9 "Creating a empty data to avoid nullptr"
#define CONF_FILE_NOTICE_MSG "# Config File\n# Use 'var' to create variable\n# e.g.: var name=string=Daniel\n# All four kinds of type:int bool string void"
#define TS_ID_10 "Check is there so many "
#define TS_ID_11 "sign"
#define TS_ID_12 "Can't open file"
#define TS_ID_13 "The library has not loaded !"
#define TS_ID_14 "The library is not exist!"